//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beerApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeerVariety
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeerVariety()
        {
            this.BeerConsume = new HashSet<BeerConsume>();
        }
    
        public int IdBeerVariety { get; set; }
        public int IdBeer { get; set; }
        public string Description { get; set; }
        public decimal PerAcohol { get; set; }
        public int IdType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeerConsume> BeerConsume { get; set; }
        public virtual BeerHeader BeerHeader { get; set; }
    }
}
