//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beerApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeerConsume
    {
        public int IdBeerConsume { get; set; }
        public int IdBeerVariety { get; set; }
        public int IdUser { get; set; }
        public System.DateTime DateConsume { get; set; }
    
        public virtual BeerVariety BeerVariety { get; set; }
        public virtual Users Users { get; set; }
    }
}
