//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace beerApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeerEntities : DbContext
    {
        public BeerEntities()
            : base("name=BeerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeerConsume> BeerConsume { get; set; }
        public virtual DbSet<BeerHeader> BeerHeader { get; set; }
        public virtual DbSet<BeerVariety> BeerVariety { get; set; }
        public virtual DbSet<Catalog> Catalog { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
